//! Built-in actions dispatched through the `sol-actions.wasm` binary.
//!
//! These actions do not have native handlers in `sol-manager`; they are
//! always executed by `crate::wasm_host::exec` once the WASM artifact is
//! loaded. They cover:
//!
//! * Document / action / artifact / type CRUD
//! * Document field operations, references
//! * Entity search
//! * Action execution (`exec action`)
//! * Filesystem operations (read, write, copy, directory list)
//! * Environment variable storage (non-secret only)
//! * Scoped, encrypted secret storage
//! * URL fetch and fetch-and-extract
//! * Model CRUD and LLM inference
//! * Permission, schedule, knowledge-base CRUD
//!
//! Seeding is automatic — the `WasmActionsProvider` is registered with
//! the global registry at manager construction time.

use sol_core::builtin_actions::{BuiltinAction, BuiltinActionsProvider, WASM_BIN};

// ── Catalogue ────────────────────────────────────────────────────────────────

/// Every action entry that targets the bundled WASM binary. Together with
/// the per-mod slices in extraction, inquiry, instruction, browser_handler,
/// system_browser, and loopback_control this is the union of all built-in
/// actions seeded into the database.
pub const BUILTIN_ACTIONS: &[BuiltinAction] = &[
    // ── Document CRUD ────────────────────────────────────────────────────────
    BuiltinAction {
        name: "new document",
        fn_name: Some("entity_new_document"),
        bin_name: Some(WASM_BIN),
        phrases: &[
            "new document",
            "create document",
            "add document",
            "make document",
        ],
        description: "Create a new document with the given fields and type.",
        model_instructions: None,
        parameter_type_name: None,
        result_type_name: None,
        destructive: None,
    },
    BuiltinAction {
        name: "get document",
        fn_name: Some("entity_get_document"),
        bin_name: Some(WASM_BIN),
        phrases: &[
            "get document",
            "find document",
            "retrieve document",
            "show document",
            "fetch document",
        ],
        description: "Retrieve a document by ID or name.",
        model_instructions: None,
        parameter_type_name: None,
        result_type_name: None,
        destructive: None,
    },
    BuiltinAction {
        name: "set document",
        fn_name: Some("entity_set_document"),
        bin_name: Some(WASM_BIN),
        phrases: &[
            "update document",
            "edit document",
            "set document",
            "modify document",
            "change document",
        ],
        description: "Update fields on an existing document.",
        model_instructions: None,
        parameter_type_name: None,
        result_type_name: None,
        destructive: None,
    },
    BuiltinAction {
        name: "delete document",
        fn_name: Some("entity_delete_document"),
        bin_name: Some(WASM_BIN),
        phrases: &[
            "delete document",
            "remove document",
            "trash document",
            "discard document",
        ],
        description: "Permanently delete a document by ID.",
        model_instructions: None,
        parameter_type_name: None,
        result_type_name: None,
        destructive: None,
    },
    BuiltinAction {
        name: "list documents",
        fn_name: Some("entity_list_documents"),
        bin_name: Some(WASM_BIN),
        phrases: &[
            "list documents",
            "show documents",
            "all documents",
            "browse documents",
        ],
        description: "List documents, optionally filtered by type or query.",
        model_instructions: None,
        parameter_type_name: Some("ListOptions"),
        result_type_name: None,
        destructive: None,
    },
    // ── Action CRUD ──────────────────────────────────────────────────────────
    BuiltinAction {
        name: "new action",
        fn_name: Some("entity_new_action"),
        bin_name: Some(WASM_BIN),
        phrases: &[
            "new action",
            "create action",
            "add action",
            "make action",
            "define action",
        ],
        description: "Register a new action with its name, phrases, and handler configuration.",
        model_instructions: None,
        parameter_type_name: None,
        result_type_name: None,
        destructive: None,
    },
    BuiltinAction {
        name: "get action",
        fn_name: Some("entity_get_action"),
        bin_name: Some(WASM_BIN),
        phrases: &[
            "get action",
            "find action",
            "show action",
            "retrieve action",
        ],
        description: "Retrieve an action by name or ID.",
        model_instructions: None,
        parameter_type_name: None,
        result_type_name: None,
        destructive: None,
    },
    BuiltinAction {
        name: "set action",
        fn_name: Some("entity_set_action"),
        bin_name: Some(WASM_BIN),
        phrases: &[
            "update action",
            "edit action",
            "set action",
            "modify action",
        ],
        description: "Update an existing action's configuration or metadata.",
        model_instructions: None,
        parameter_type_name: None,
        result_type_name: None,
        destructive: None,
    },
    BuiltinAction {
        name: "delete action",
        fn_name: Some("entity_delete_action"),
        bin_name: Some(WASM_BIN),
        phrases: &[
            "delete action",
            "remove action",
            "trash action",
            "discard action",
        ],
        description: "Permanently delete an action record.",
        model_instructions: None,
        parameter_type_name: None,
        result_type_name: None,
        destructive: None,
    },
    BuiltinAction {
        name: "list actions",
        fn_name: Some("entity_list_actions"),
        bin_name: Some(WASM_BIN),
        phrases: &[
            "list actions",
            "show actions",
            "all actions",
            "browse actions",
        ],
        description: "List all registered actions, optionally filtered.",
        model_instructions: None,
        parameter_type_name: Some("ListOptions"),
        result_type_name: None,
        destructive: None,
    },
    // ── Artifact CRUD ────────────────────────────────────────────────────────
    BuiltinAction {
        name: "new artifact",
        fn_name: Some("entity_new_artifact"),
        bin_name: Some(WASM_BIN),
        phrases: &[
            "new artifact",
            "create artifact",
            "upload artifact",
            "add artifact",
        ],
        description: "Create a new artifact record (binary or text blob).",
        model_instructions: None,
        parameter_type_name: None,
        result_type_name: None,
        destructive: None,
    },
    BuiltinAction {
        name: "get artifact",
        fn_name: Some("entity_get_artifact"),
        bin_name: Some(WASM_BIN),
        phrases: &[
            "get artifact",
            "find artifact",
            "show artifact",
            "retrieve artifact",
        ],
        description: "Retrieve an artifact by ID or name.",
        model_instructions: None,
        parameter_type_name: None,
        result_type_name: None,
        destructive: None,
    },
    BuiltinAction {
        name: "set artifact",
        fn_name: Some("entity_set_artifact"),
        bin_name: Some(WASM_BIN),
        phrases: &[
            "update artifact",
            "edit artifact",
            "set artifact",
            "modify artifact",
        ],
        description: "Update metadata for an existing artifact.",
        model_instructions: None,
        parameter_type_name: None,
        result_type_name: None,
        destructive: None,
    },
    BuiltinAction {
        name: "delete artifact",
        fn_name: Some("entity_delete_artifact"),
        bin_name: Some(WASM_BIN),
        phrases: &[
            "delete artifact",
            "remove artifact",
            "trash artifact",
            "discard artifact",
        ],
        description: "Permanently delete an artifact record.",
        model_instructions: None,
        parameter_type_name: None,
        result_type_name: None,
        destructive: None,
    },
    BuiltinAction {
        name: "list artifacts",
        fn_name: Some("entity_list_artifacts"),
        bin_name: Some(WASM_BIN),
        phrases: &[
            "list artifacts",
            "all artifacts",
            "show artifacts",
            "browse artifacts",
        ],
        description: "List stored artifacts, optionally filtered.",
        model_instructions: None,
        parameter_type_name: Some("ListOptions"),
        result_type_name: None,
        destructive: None,
    },
    BuiltinAction {
        name: "upload file artifact",
        fn_name: Some("artifact_upload_file"),
        bin_name: Some(WASM_BIN),
        phrases: &[
            "upload file artifact",
            "upload artifact",
            "create artifact from file",
            "store file as artifact",
        ],
        description: "Upload a file from disk and store it as an artifact.",
        model_instructions: None,
        parameter_type_name: None,
        result_type_name: None,
        destructive: None,
    },
    // ── Type CRUD ────────────────────────────────────────────────────────────
    BuiltinAction {
        name: "new type",
        fn_name: Some("entity_new_type"),
        bin_name: Some(WASM_BIN),
        phrases: &[
            "new type",
            "create type",
            "define type",
            "add type",
            "make type",
        ],
        description: "Define a new document type with its schema.",
        model_instructions: None,
        parameter_type_name: None,
        result_type_name: None,
        destructive: None,
    },
    BuiltinAction {
        name: "get type",
        fn_name: Some("entity_get_type"),
        bin_name: Some(WASM_BIN),
        phrases: &["get type", "find type", "show type", "retrieve type"],
        description: "Retrieve a type definition by name or ID.",
        model_instructions: None,
        parameter_type_name: None,
        result_type_name: None,
        destructive: None,
    },
    BuiltinAction {
        name: "set type",
        fn_name: Some("entity_set_type"),
        bin_name: Some(WASM_BIN),
        phrases: &["update type", "edit type", "set type", "modify type"],
        description: "Update the schema or metadata for an existing type.",
        model_instructions: None,
        parameter_type_name: None,
        result_type_name: None,
        destructive: None,
    },
    BuiltinAction {
        name: "delete type",
        fn_name: Some("entity_delete_type"),
        bin_name: Some(WASM_BIN),
        phrases: &["delete type", "remove type", "trash type", "discard type"],
        description: "Remove a type definition.",
        model_instructions: None,
        parameter_type_name: None,
        result_type_name: None,
        destructive: None,
    },
    BuiltinAction {
        name: "list types",
        fn_name: Some("entity_list_types"),
        bin_name: Some(WASM_BIN),
        phrases: &["list types", "all types", "show types", "browse types"],
        description: "List all defined types.",
        model_instructions: None,
        parameter_type_name: Some("ListOptions"),
        result_type_name: None,
        destructive: None,
    },
    // ── Reference entities ───────────────────────────────────────────────────
    BuiltinAction {
        name: "new doc ref",
        fn_name: Some("entity_new_doc_ref"),
        bin_name: Some(WASM_BIN),
        phrases: &[
            "new doc ref",
            "add document reference",
            "link document",
            "create document link",
            "reference document",
        ],
        description: "Create a reference link from one document to another.",
        model_instructions: None,
        parameter_type_name: None,
        result_type_name: None,
        destructive: None,
    },
    BuiltinAction {
        name: "new action ref",
        fn_name: Some("entity_new_action_ref"),
        bin_name: Some(WASM_BIN),
        phrases: &[
            "new action ref",
            "add action reference",
            "link action",
            "create action link",
            "reference action",
        ],
        description: "Create a reference link from a document to an action.",
        model_instructions: None,
        parameter_type_name: None,
        result_type_name: None,
        destructive: None,
    },
    // ── Document field operations ────────────────────────────────────────────
    BuiltinAction {
        name: "document get field",
        fn_name: Some("get_field"),
        bin_name: Some(WASM_BIN),
        phrases: &[
            "get field",
            "read field",
            "get document field",
            "fetch field",
            "retrieve field",
        ],
        description: "Read a single field value from a document.",
        model_instructions: None,
        parameter_type_name: None,
        result_type_name: None,
        destructive: None,
    },
    BuiltinAction {
        name: "document set field",
        fn_name: Some("set_field"),
        bin_name: Some(WASM_BIN),
        phrases: &[
            "set field",
            "write field",
            "update field",
            "set document field",
            "change field",
        ],
        description: "Write or update a single field value on a document.",
        model_instructions: None,
        parameter_type_name: None,
        result_type_name: None,
        destructive: None,
    },
    BuiltinAction {
        name: "attach artifact to document",
        fn_name: Some("document_attach_artifact"),
        bin_name: Some(WASM_BIN),
        phrases: &[
            "attach artifact to document",
            "add artifact to document",
            "link artifact to document",
            "associate artifact with document",
        ],
        description: "Associate a stored artifact with a document.",
        model_instructions: None,
        parameter_type_name: None,
        result_type_name: None,
        destructive: None,
    },
    // ── Entity search ────────────────────────────────────────────────────────
    BuiltinAction {
        name: "entity search",
        fn_name: Some("entity_search"),
        bin_name: Some(WASM_BIN),
        phrases: &[
            "search entities",
            "find entity",
            "entity search",
            "search records",
            "look up entity",
        ],
        description: "Full-text search across entities by name, caption, or content.",
        model_instructions: None,
        parameter_type_name: None,
        result_type_name: None,
        destructive: None,
    },
    // ── Action execution ─────────────────────────────────────────────────────
    BuiltinAction {
        name: "exec action",
        fn_name: Some("entity_exec_action"),
        bin_name: Some(WASM_BIN),
        phrases: &[
            "run action",
            "execute action",
            "exec action",
            "dispatch action",
            "invoke action",
        ],
        description: "Execute a named action with the given parameters.",
        model_instructions: None,
        parameter_type_name: None,
        result_type_name: None,
        destructive: None,
    },
    // ── Filesystem / system operations ───────────────────────────────────────
    BuiltinAction {
        name: "file read",
        fn_name: Some("file_read"),
        bin_name: Some(WASM_BIN),
        phrases: &[
            "read file",
            "open file",
            "get file contents",
            "load file",
            "view file",
        ],
        description: "Read the contents of a file from disk.",
        model_instructions: None,
        parameter_type_name: None,
        result_type_name: None,
        // Read-only — not destructive despite the `filesystem` category.
        destructive: Some(false),
    },
    BuiltinAction {
        name: "file write",
        fn_name: Some("file_write"),
        bin_name: Some(WASM_BIN),
        phrases: &[
            "write file",
            "save file",
            "write to file",
            "store to file",
            "output to file",
        ],
        description: "Write content to a file on disk.",
        model_instructions: None,
        parameter_type_name: None,
        result_type_name: None,
        destructive: None,
    },
    BuiltinAction {
        name: "directory list",
        fn_name: Some("dir_list"),
        bin_name: Some(WASM_BIN),
        phrases: &[
            "list directory",
            "list files",
            "browse files",
            "show directory",
            "ls directory",
        ],
        description: "List files and subdirectories in a directory.",
        model_instructions: None,
        parameter_type_name: None,
        result_type_name: None,
        // Read-only listing — not destructive despite the `filesystem` category.
        destructive: Some(false),
    },
    BuiltinAction {
        name: "file copy",
        fn_name: Some("file_copy"),
        bin_name: Some(WASM_BIN),
        phrases: &["copy file", "duplicate file", "file copy", "clone file"],
        description: "Copy a file to a new location.",
        model_instructions: None,
        parameter_type_name: None,
        result_type_name: None,
        destructive: None,
    },
    BuiltinAction {
        name: "directory copy",
        fn_name: Some("dir_copy"),
        bin_name: Some(WASM_BIN),
        phrases: &[
            "copy directory",
            "copy folder",
            "directory copy",
            "duplicate folder",
        ],
        description: "Recursively copy a directory to a new location.",
        model_instructions: None,
        parameter_type_name: None,
        result_type_name: None,
        destructive: None,
    },
    BuiltinAction {
        name: "get environment variable",
        fn_name: Some("get_env"),
        bin_name: Some(WASM_BIN),
        phrases: &[
            "get env",
            "environment variable",
            "get environment variable",
            "read env var",
            "get env var",
        ],
        description: "Read the value of an environment variable by name.",
        model_instructions: None,
        parameter_type_name: None,
        result_type_name: None,
        destructive: None,
    },
    BuiltinAction {
        name: "set environment variable",
        fn_name: Some("set_env"),
        bin_name: Some(WASM_BIN),
        phrases: &[
            "set env",
            "set environment variable",
            "write env var",
            "store env var",
            "persist env var",
        ],
        description: "Write a key/value pair to the WASM environment store. The value is persisted to sol-config.json so it survives restarts. Do not use this for secrets — every WASM guest shares this store; use `set secret` instead.",
        model_instructions: Some(
            "Persist a single non-sensitive env key/value pair (feature flags, non-secret IDs). The store is shared with all WASM guests via the `get-env` / `set-env` WIT imports, so it must never hold credentials, tokens, or other secrets — use `set secret` / `get secret` for those instead. To delete a key, pass an empty `value`.",
        ),
        parameter_type_name: None,
        result_type_name: None,
        destructive: None,
    },
    BuiltinAction {
        name: "get secret",
        fn_name: Some("get_secret"),
        bin_name: Some(WASM_BIN),
        phrases: &[
            "get secret",
            "read secret",
            "retrieve secret",
        ],
        description: "Read a secret by name, scoped to the calling action. Unlike `get environment variable`, this only returns a value if the calling action's own `action_config.secrets` map declares a decryption key for that name — other actions cannot read it even if they know the name.",
        model_instructions: Some(
            "Read a secret previously stored with `set secret` (e.g. OAuth `client_secret`/`refresh_token` after a login-to-google flow). Returns null if the calling action has no key configured for that secret name in its own `action_config.secrets` map, or if nothing has been stored under that name yet.",
        ),
        parameter_type_name: None,
        result_type_name: None,
        destructive: None,
    },
    BuiltinAction {
        name: "set secret",
        fn_name: Some("set_secret"),
        bin_name: Some(WASM_BIN),
        phrases: &[
            "set secret",
            "store secret",
            "persist secret",
        ],
        description: "Encrypt and store a secret by name, scoped to the calling action. The calling action's own `action_config.secrets` map must already declare a key for that name — this action does not grant access, it only writes under a key the caller was already configured with.",
        model_instructions: Some(
            "Persist a single secret key/value pair (e.g. OAuth `client_id`/`client_secret`/`scope`/`refresh_token` after a login-to-google flow). Fails if the calling action has no key configured for that name in its own `action_config.secrets` map — an action must be set up with a `secrets` entry before it can call this.",
        ),
        parameter_type_name: None,
        result_type_name: None,
        destructive: None,
    },
    BuiltinAction {
        name: "fetch html",
        fn_name: Some("fetch_html"),
        bin_name: Some(WASM_BIN),
        phrases: &[
            "fetch html",
            "download html",
            "get page html",
            "fetch page source",
            "get html source",
        ],
        description: "Download the raw HTML source of a web page.",
        model_instructions: None,
        parameter_type_name: None,
        result_type_name: None,
        destructive: None,
    },
    BuiltinAction {
        name: "fetch and extract",
        fn_name: Some("fetch_and_extract"),
        bin_name: Some(WASM_BIN),
        phrases: &[
            "fetch and extract",
            "extract from url",
            "fetch url and extract",
            "extract web page",
            "scrape and extract",
        ],
        description: "Fetch a web page and extract its structured content.",
        model_instructions: Some(
            "Uses a raw HTTP request (reqwest) — NO JavaScript execution, no cookies/session from the browser. Works for static pages and APIs, but will return empty/minimal content for SPAs (React, Reddit, etc.) that require JS rendering, and can't see content behind a login the browser session already has. Prefer `extract webpage document` (browser-based, one step) unless the instruction's wording clearly asks for a raw request ('fetch', 'download', 'GET request', 'API', 'http request') rather than 'browse'/'visit'/'page'/'website'/'browser'. `source_document_name` is REQUIRED — never omit it. Use a stable slug derived from the URL (e.g. for https://example.com/page use `example_com_page`). If the instruction references a knowledge base, pass `knowledge_base_name` in every call; otherwise derive one from the base domain and reuse it across all extraction steps. Pass `extraction_prompt` (free text) if the instruction wants specific content emphasized, filtered, or shaped a certain way — e.g. 'focus on the comments' or 'use the Invoice type, omit boilerplate'.",
        ),
        parameter_type_name: None,
        result_type_name: None,
        destructive: None,
    },
    // ── Model CRUD ───────────────────────────────────────────────────────────
    BuiltinAction {
        name: "new model",
        fn_name: Some("entity_new_model"),
        bin_name: Some(WASM_BIN),
        phrases: &[
            "new model",
            "create model",
            "add model",
            "register model",
            "define model",
        ],
        description: "Register a new language model configuration.",
        model_instructions: None,
        parameter_type_name: None,
        result_type_name: None,
        destructive: None,
    },
    BuiltinAction {
        name: "get model",
        fn_name: Some("entity_get_model"),
        bin_name: Some(WASM_BIN),
        phrases: &["get model", "find model", "show model", "retrieve model"],
        description: "Retrieve a model configuration by name or ID.",
        model_instructions: None,
        parameter_type_name: None,
        result_type_name: None,
        destructive: None,
    },
    BuiltinAction {
        name: "set model",
        fn_name: Some("entity_set_model"),
        bin_name: Some(WASM_BIN),
        phrases: &["update model", "edit model", "set model", "modify model"],
        description: "Update an existing model's endpoint or configuration.",
        model_instructions: None,
        parameter_type_name: None,
        result_type_name: None,
        destructive: None,
    },
    BuiltinAction {
        name: "delete model",
        fn_name: Some("entity_delete_model"),
        bin_name: Some(WASM_BIN),
        phrases: &[
            "delete model",
            "remove model",
            "trash model",
            "discard model",
        ],
        description: "Remove a model configuration record.",
        model_instructions: None,
        parameter_type_name: None,
        result_type_name: None,
        destructive: None,
    },
    BuiltinAction {
        name: "list models",
        fn_name: Some("entity_list_models"),
        bin_name: Some(WASM_BIN),
        phrases: &["list models", "show models", "all models", "browse models"],
        description: "List all registered model configurations.",
        model_instructions: None,
        parameter_type_name: Some("ListOptions"),
        result_type_name: None,
        destructive: None,
    },
    // ── Permission CRUD ──────────────────────────────────────────────────────
    BuiltinAction {
        name: "new permission",
        fn_name: Some("entity_new_permission"),
        bin_name: Some(WASM_BIN),
        phrases: &[
            "new permission",
            "create permission",
            "add permission",
            "define permission",
        ],
        description: "Create a new permission with its grants and constraints.",
        model_instructions: None,
        parameter_type_name: None,
        result_type_name: None,
        destructive: None,
    },
    BuiltinAction {
        name: "get permission",
        fn_name: Some("entity_get_permission"),
        bin_name: Some(WASM_BIN),
        phrases: &[
            "get permission",
            "find permission",
            "show permission",
            "retrieve permission",
        ],
        description: "Retrieve a permission definition by name.",
        model_instructions: None,
        parameter_type_name: None,
        result_type_name: None,
        destructive: None,
    },
    BuiltinAction {
        name: "set permission",
        fn_name: Some("entity_set_permission"),
        bin_name: Some(WASM_BIN),
        phrases: &[
            "update permission",
            "edit permission",
            "set permission",
            "modify permission",
        ],
        description: "Update a permission's grants or child permissions.",
        model_instructions: None,
        parameter_type_name: None,
        result_type_name: None,
        destructive: None,
    },
    BuiltinAction {
        name: "delete permission",
        fn_name: Some("entity_delete_permission"),
        bin_name: Some(WASM_BIN),
        phrases: &[
            "delete permission",
            "remove permission",
            "revoke permission",
            "discard permission",
        ],
        description: "Remove a permission record.",
        model_instructions: None,
        parameter_type_name: None,
        result_type_name: None,
        destructive: None,
    },
    BuiltinAction {
        name: "list permissions",
        fn_name: Some("entity_list_permissions"),
        bin_name: Some(WASM_BIN),
        phrases: &[
            "list permissions",
            "show permissions",
            "all permissions",
            "browse permissions",
        ],
        description: "List all defined permissions.",
        model_instructions: None,
        parameter_type_name: Some("ListOptions"),
        result_type_name: None,
        destructive: None,
    },
    // ── Schedule CRUD ────────────────────────────────────────────────────────
    BuiltinAction {
        name: "new schedule",
        fn_name: Some("entity_new_schedule"),
        bin_name: Some(WASM_BIN),
        phrases: &[
            "new schedule",
            "create schedule",
            "add schedule",
            "set up schedule",
        ],
        description: "Create a new scheduled task with its cron expression and action.",
        model_instructions: None,
        parameter_type_name: None,
        result_type_name: None,
        destructive: None,
    },
    BuiltinAction {
        name: "get schedule",
        fn_name: Some("entity_get_schedule"),
        bin_name: Some(WASM_BIN),
        phrases: &[
            "get schedule",
            "find schedule",
            "show schedule",
            "retrieve schedule",
        ],
        description: "Retrieve a schedule by name or ID.",
        model_instructions: None,
        parameter_type_name: None,
        result_type_name: None,
        destructive: None,
    },
    BuiltinAction {
        name: "set schedule",
        fn_name: Some("entity_set_schedule"),
        bin_name: Some(WASM_BIN),
        phrases: &[
            "update schedule",
            "edit schedule",
            "set schedule",
            "modify schedule",
        ],
        description: "Update a schedule's timing or action configuration.",
        model_instructions: None,
        parameter_type_name: None,
        result_type_name: None,
        destructive: None,
    },
    BuiltinAction {
        name: "delete schedule",
        fn_name: Some("entity_delete_schedule"),
        bin_name: Some(WASM_BIN),
        phrases: &[
            "delete schedule",
            "remove schedule",
            "cancel schedule",
            "discard schedule",
        ],
        description: "Remove a scheduled task.",
        model_instructions: None,
        parameter_type_name: None,
        result_type_name: None,
        destructive: None,
    },
    BuiltinAction {
        name: "list schedules",
        fn_name: Some("entity_list_schedules"),
        bin_name: Some(WASM_BIN),
        phrases: &[
            "list schedules",
            "show schedules",
            "all schedules",
            "browse schedules",
        ],
        description: "List all scheduled tasks.",
        model_instructions: None,
        parameter_type_name: Some("ListOptions"),
        result_type_name: None,
        destructive: None,
    },
    // ── KnowledgeBase / Catalog CRUD ─────────────────────────────────────────
    BuiltinAction {
        name: "new knowledge base",
        fn_name: Some("entity_new_knowledge_base"),
        bin_name: Some(WASM_BIN),
        phrases: &[
            "new knowledge base",
            "create knowledge base",
            "add knowledge base",
            "new catalog",
            "create catalog",
            "add catalog",
        ],
        description: "Create a new knowledge base (catalog) for organizing documents.",
        model_instructions: None,
        parameter_type_name: None,
        result_type_name: None,
        destructive: None,
    },
    BuiltinAction {
        name: "get knowledge base",
        fn_name: Some("entity_get_knowledge_base"),
        bin_name: Some(WASM_BIN),
        phrases: &[
            "get knowledge base",
            "find knowledge base",
            "show knowledge base",
            "get catalog",
            "find catalog",
            "show catalog",
        ],
        description: "Retrieve a knowledge base by name or ID.",
        model_instructions: None,
        parameter_type_name: None,
        result_type_name: None,
        destructive: None,
    },
    BuiltinAction {
        name: "set knowledge base",
        fn_name: Some("entity_set_knowledge_base"),
        bin_name: Some(WASM_BIN),
        phrases: &[
            "update knowledge base",
            "edit knowledge base",
            "set knowledge base",
            "update catalog",
            "edit catalog",
            "set catalog",
        ],
        description: "Update a knowledge base's configuration or metadata.",
        model_instructions: None,
        parameter_type_name: None,
        result_type_name: None,
        destructive: None,
    },
    BuiltinAction {
        name: "delete knowledge base",
        fn_name: Some("entity_delete_knowledge_base"),
        bin_name: Some(WASM_BIN),
        phrases: &[
            "delete knowledge base",
            "remove knowledge base",
            "delete catalog",
            "remove catalog",
        ],
        description: "Remove a knowledge base.",
        model_instructions: None,
        parameter_type_name: None,
        result_type_name: None,
        destructive: None,
    },
    BuiltinAction {
        name: "list knowledge bases",
        fn_name: Some("entity_list_knowledge_bases"),
        bin_name: Some(WASM_BIN),
        phrases: &[
            "list knowledge bases",
            "show knowledge bases",
            "all knowledge bases",
            "list catalogs",
            "show catalogs",
            "all catalogs",
        ],
        description: "List all knowledge bases.",
        model_instructions: None,
        parameter_type_name: Some("ListOptions"),
        result_type_name: None,
        destructive: None,
    },
    // ── LLM inference ────────────────────────────────────────────────────────
    BuiltinAction {
        name: "model chat",
        fn_name: Some("model_chat"),
        bin_name: Some(WASM_BIN),
        phrases: &[
            "chat with model",
            "ask model",
            "llm chat",
            "model chat",
            "send message to model",
        ],
        description: "Send a chat message to a language model and receive a response.",
        model_instructions: Some(
            "Params MUST include `model_name` (use `\"instructor\"`) and `messages`: an array like [{\"role\":\"user\",\"content\":\"...\"}]. Put both as top-level keys — do NOT use `in` as a key or wrap params in a sub-object. To feed a file or a prior step's output to the model, embed `$.step_N.result` inside the message content (add a `file read` step first when the source is a file). Returns the assistant's reply text (a string); reference it downstream as `$.step_N.result`. This (or `model generate`) is the tool for pulling a SPECIFIC, custom-shaped piece of data out of any prior step's result (a list of links, one URL, a title, a summary) — the `extract *` actions cannot do this, they have a fixed pipeline with no prompt/instructions field.",
        ),
        parameter_type_name: None,
        result_type_name: None,
        destructive: None,
    },
    BuiltinAction {
        name: "model generate",
        fn_name: Some("model_generate"),
        bin_name: Some(WASM_BIN),
        phrases: &[
            "generate text",
            "model generate",
            "llm generate",
            "text completion",
            "prompt model",
        ],
        description: "Generate text from a prompt using a language model.",
        model_instructions: Some(
            "Params MUST include `model_name` (use `\"instructor\"`) and `prompt`, both as top-level keys — never wrap them in an `in`/`input` object. The most common use is turning a `dom snapshot`/`dom query` result into structured data: {\"model_name\":\"instructor\",\"prompt\":\"Extract <field> from each element and return a JSON array. No markdown. Input: $.step_N.result\"}, then feed that array to a `__for__` loop's `each`. For a single pagination/next-page href, ask it to return only the URL string or null. Returns the generated text (a string); reference it downstream as `$.step_N.result`. This (or `model chat`) is the tool for pulling a SPECIFIC, custom-shaped piece of data out of any prior step's result — the `extract *` actions cannot do this, they have a fixed pipeline with no prompt/instructions field; don't invent one on them.",
        ),
        parameter_type_name: None,
        result_type_name: None,
        destructive: None,
    },
    BuiltinAction {
        name: "list available models",
        fn_name: Some("model_list"),
        bin_name: Some(WASM_BIN),
        phrases: &[
            "list available models",
            "model list",
            "what models are available",
            "show available models",
        ],
        description: "List language models currently available for inference.",
        model_instructions: None,
        parameter_type_name: None,
        result_type_name: None,
        destructive: None,
    },
];

// ── Provider ─────────────────────────────────────────────────────────────────

/// Provider that contributes the WASM-dispatched actions to the
/// built-in action registry.
pub struct WasmActionsProvider;

impl BuiltinActionsProvider for WasmActionsProvider {
    fn source_name(&self) -> &'static str {
        "wasm"
    }

    fn actions(&self) -> Vec<BuiltinAction> {
        BUILTIN_ACTIONS.to_vec()
    }
}

